#!/usr/bin/env python3
# -*- coding: utf8 -*-

# pylint: disable=invalid-name                    # [C0103] single letter var names, name too descriptive
from __future__ import annotations
import sys
import logging
import time
from asserttool import ic
from decimal import Decimal
import sh
#from decimal import InvalidOperation
#from eprint import eprint
#from shlex import quote
#import os
logging.basicConfig(level=logging.INFO)

if len(sys.argv) < 2:
    print(sys.argv[0], '[interval_in_seconds]', 'command', file=sys.stderr)
    sys.exit(1)

ignore_exit_code = False
if sys.argv[0] == "dodo-force":
    ignore_exit_code = True

delay = Decimal(sys.argv[1])

while True:
    _program = sys.argv[2]
    ic(_program)
    _program_path = sh.which(_program).strip()
    ic(_program_path)

    _command = sh.Command(_program_path)
    for _arg in sys.argv[3:]:
        _command = _command.bake(_arg)

    if ignore_exit_code:
        _command(_fg=True, _ok_code=list(range(255)))
    else:
        _command(_fg=True)
    time.sleep(float(delay))
