#!/bin/sh

is_number()
{
    #echo "${1}" | grep -q "^-\?[0-9]*$"
    echo "${1}" | grep -q "^[0-9]+([.][0-9]+)?$"
}

argcount=1
usage="interval_in_seconds command"
test "$#" -ge "${argcount}" || { echo "$0 ${usage}" > /dev/stderr && exit 1 ; } #"-ge=>=" "-gt=>" "-le=<=" "-lt=<" "-ne=!="

if is_number "${1}";
then
    seconds="${1}"
    shift
else
    seconds=1   # default
fi

set -o nounset

random="0"

if [ "${seconds}" == "--random" ];
then
    random="1"
    #seconds=`shuf -i 1-100 -n 1`
    #echo "${seconds}" > /dev/stderr
fi


while :
do
    if [ "${random}" == "1" ];
    then
        seconds=`shuf -i 1-100 -n 1`
        #echo "random: ${seconds}" > /dev/stderr
    fi
    #echo "${seconds}" > /dev/stderr
    sleep "${seconds}" || exit 1
    "${@}"
    #seconds=`shuf -i 1-100 -n 1`
done
