#!/usr/bin/env python3

from __future__ import annotations

import os
import sys
import time
from decimal import Decimal

import hs


if len(sys.argv) < 4:
    print(
        f"Usage: {sys.argv[0]} <interval_seconds> <count> <command> [args...]",
        file=sys.stderr,
    )
    sys.exit(1)

ignore_exit_code = os.path.basename(sys.argv[0]) == "dodo-force"

delay = Decimal(sys.argv[1])
count = Decimal(sys.argv[2])

i = 0
while True:
    i += 1
    _program = sys.argv[3]
    _program_path = hs.Command("which")(_program).strip()

    _command = hs.Command(_program_path)
    for _arg in sys.argv[4:]:
        _command.bake(_arg)

    if ignore_exit_code:
        _command(_fg=True, _ok_code=range(256))
    else:
        _command(_fg=True)
    time.sleep(float(delay))
    if i == count:
        break
